### ISSUE TITLE
About gTTS limitation

### ISSUE THREAD

**Issue by Yoshiko-Arsenault** [thu-coai/LAUG#3]
When I run TTS step in SR task, the following error occurs:
```
gtts.tts.gTTSError: 429 (Too Many Requests) from TTS API.
```
This is because Google thinks I am a crawler robot, which limits my IP address.
I want to know if you have used some special methods for requesting gTTS to obtain all audios of whole dataset?

**Comment by hualai-liujiexi** [comment]
We add 0.5~1s sleep between requests while processing a large amount of data.

**Comment by Yoshiko-Arsenault** [comment]
Thanks.
