### ISSUE TITLE
Pretrained weight for NLU

### ISSUE THREAD

**Issue by BigPigKing** [thu-coai/LAUG#5]
Hello, 

I have followed the instructions below to build LAUG:

1. Download data and put it into correct directory
2. cd to "**LAUG/nlu/jointBERT_new/multiwoz**" and doing the preprocess for ["usr", "sys", "all"]
3. Download the models described in "**LAUG/nlu/jointBERT_new/multiwoz/README.md**"
4. Unzip and put them into correct directory
5. Test the NLU using "**_python3 test.py --config_path multiwoz/configs/multiwoz_usr.json_**"

During the loading of the pretrained weight, I get:
<img width="1440" alt="截圖 2021-08-19 下午2 01 51" src="https://user-images.githubusercontent.com/24654041/130016091-96d0a03c-748f-4ea9-bb01-ea41a88544c5.png">

And I guess the provided pretrained weight is not suitable for MultiWoz 2.3 or I have missed some important step?

I also noticed that in "**LAUG/nlu/jointBERT_new/multiwoz/nlu.py**" there are exist a url "https://convlab.blob.core.windows.net/convlab-2/bert_multiwoz_new_context.zip", and I try to load and test it via
"**_python3 test.py --config_path multiwoz/configs/multiwoz_new_context.json_**"

But I still get the mismatched:
<img width="1440" alt="截圖 2021-08-19 下午2 11 14" src="https://user-images.githubusercontent.com/24654041/130017025-0d71a2f0-787b-492d-98b0-762936a870b8.png">

Thanks

**Comment by hualai-liujiexi** [comment]
The pre-trained model is for usr only. Did you run preprocess.py with 'usr' mode?
Thanks
